[book]
title = "Engineering Playbook"
authors = ["vnykmshr"]
description = "Command reference for the Engineering Playbook"
language = "en"
src = "."

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/vnykmshr/playbook"
site-url = "/playbook/"
no-section-label = true

[output.html.search]
limit-results = 20

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
editable = false
